### ISSUE TITLE
Insertition using format

### ISSUE THREAD

**Issue by dmitry-medvediev** [kshvakov/clickhouse#20]
Using clickhouse-client I am able to do insert requests like
```
INSERT INTO mydb.events FORMAT CSV 8cd3e02c-83b1-41f0-8e29-c1681f03feb0,1a9cbce7-0788-430e-b3e7-15bbbea2ac27,3,0,0,0.000010,0.200000,,2017-02-27,1488203857,4,3,3,4,0,0,4,0,,,Unknown,Linux Unknown,0,0,[],,,0,0,0,,127.0.0.1,0,0,0,,0,,0,0,0,,,,,,,,,,,,,[]
```
But when I`m trying to perform this request using your driver I have panic.

My code
```
package main

import (
	"database/sql"
	"fmt"
	"github.com/kshvakov/clickhouse"
	"log"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	if err != nil {
		log.Fatal(err)
	}
	if err := connect.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			fmt.Printf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		} else {
			fmt.Println(err)
		}
		return
	}
	tx, err := connect.Begin()
	if err != nil {
		log.Fatal(err)
	}
	_, err = tx.Exec(`INSERT INTO mydb.events FORMAT CSV 8cd3e02c-83b1-41f0-8e29-c1681f03feb0,1a9cbce7-0788-430e-b3e7-15bbbea2ac27,3,0,0,0.000010,0.200000,,2017-02-27,1488203857,4,3,3,4,0,0,4,0,,,Unknown,Linux Unknown,0,0,[],,,0,0,0,,127.0.0.1,0,0,0,,0,,0,0,0,,,,,,,,,,,,,[]`)
	if err != nil {
		log.Fatal(err)
	}
	err = tx.Commit()
	if err != nil {
		log.Fatal(err)
	}
}
```
Panic: 
```
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][hello] -> Golang SQLDriver 1.1.54126
[clickhouse][hello] <- ClickHouse 1.1.54164 (Europe/Kiev)
[clickhouse]-> ping
[clickhouse]<- pong
[clickhouse][begin] tx=false, data=false
[clickhouse][prepare] INSERT INTO trackmanic2.events FORMAT CSV 8cd3e02c-83b1-41f0-8e29-c1681f03feb0,1a9cbce7-0788-430e-b3e7-15bbbea2ac27,3,0,0,0.000010,0.200000,,2017-02-27,1488203857,4,3,3,4,0,0,4,0,,,Unknown,Linux Unknown,0,0,[],,,0,0,0,,127.0.0.1,0,0,0,,0,,0,0,0,,,,,,,,,,,,,[]
[clickhouse][send query] INSERT INTO trackmanic2.events FORMAT CSV 8cd3e02c-83b1-41f0-8e29-c1681f03feb0,1a9cbce7-0788-430e-b3e7-15bbbea2ac27,3,0,0,0.000010,0.200000,,2017-02-27,1488203857,4,3,3,4,0,0,4,0,,,Unknown,Linux Unknown,0,0,[],,,0,0,0,,127.0.0.1,0,0,0,,0,,0,0,0,,,,,,,,,,,,,[] VALUES 
[clickhouse][stmt] close
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kshvakov/clickhouse.(*block).append(0xc4200d6000, 0x661ec0, 0x0, 0x0, 0x6493c8, 0x561ec0)
        /home/dmitry/golang/src/github.com/kshvakov/clickhouse/block.go:203 +0x17c8
github.com/kshvakov/clickhouse.(*stmt).execContext(0xc4200a4180, 0x632300, 0xc420010270, 0x661ec0, 0x0, 0x0, 0x1000000005288bf, 0x10175ce911b, 0x2, 0x103)
        /home/dmitry/golang/src/github.com/kshvakov/clickhouse/stmt.go:31 +0x60
github.com/kshvakov/clickhouse.(*stmt).ExecContext(0xc4200a4180, 0x632300, 0xc420010270, 0x661ec0, 0x0, 0x0, 0xc400000008, 0xc4200b6040, 0xc42004fb88, 0x4b97c5)
        /home/dmitry/golang/src/github.com/kshvakov/clickhouse/clickhouse_go18.go:38 +0x1aa
database/sql.ctxDriverStmtExec(0x632300, 0xc420010270, 0x632400, 0xc4200a4180, 0x661ec0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/database/sql/ctxutil.go:66 +0x244
database/sql.resultFromStatement(0x632300, 0xc420010270, 0xc42004fd38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1841 +0x193
database/sql.(*Tx).ExecContext(0xc4200c0000, 0x632300, 0xc420010270, 0x59469f, 0x103, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/database/sql/sql.go:1710 +0x31f
database/sql.(*Tx).Exec(0xc4200c0000, 0x59469f, 0x103, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x58c828)
        /usr/local/go/src/database/sql/sql.go:1716 +0x85
main.main()
        /home/dmitry/golang/src/main/main.go:27 +0x341
```

How can I manage with this problem?

**Comment by kshvakov** [comment]
Нативный протокол не поддерживает подобные запросы, запросы вида `INSERT INTO table FORMAT` разбираются клиентом clickhouse или на сервере если были отправлены через http. 

Нативный протокол предполагает что для загрузки данных на сервер придет запрос вида 
`INSERT INTO table VALUES` или `INSERT INTO table (a,b,c) VALUES ` после чего идет блок данных 

в вашем случае необходимо 

```go 

package main

import (
	"database/sql"
	"fmt"
	"github.com/kshvakov/clickhouse"
	"log"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	if err != nil {
		log.Fatal(err)
	}
	if err := connect.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			fmt.Printf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		} else {
			fmt.Println(err)
		}
		return
	}
	tx, err := connect.Begin()
	if err != nil {
		log.Fatal(err)
	}
	stmt, err = tx.Prepare(`INSERT INTO mydb.events`) // подготовим запрос
	if err != nil {
		log.Fatal(err)
	}
    stmt.Exec(data,data2) // <- пишем данные в буфер (блок с данными)
	err = tx.Commit() // <- отправляем на сервер
	if err != nil {
		log.Fatal(err)
	}
}
``

**Comment by dmitry-medvediev** [comment]
Спасибо большое за ответ. 
Есть еще вопрос. Вы написали:
```
Нативный протокол предполагает что для загрузки данных на сервер придет запрос вида
INSERT INTO table VALUES или INSERT INTO table (a,b,c) VALUES после чего идет блок данных
```
Пробую сделать следующим образом
```
package main

import (
	"database/sql"
	"fmt"
	"github.com/kshvakov/clickhouse"
	"log"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	if err != nil {
		log.Fatal(err)
	}
	if err := connect.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			fmt.Printf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		} else {
			fmt.Println(err)
		}
		return
	}
	tx, err := connect.Begin()
	if err != nil {
		log.Fatal(err)
	}
	stmt, err := tx.Prepare(`INSERT INTO trackmanic2.events VALUES (?, ?)`) // подготовим запрос
	if err != nil {
		log.Fatal(err)
	}
	stmt.Exec("8cd3e02c-83b1-41f0-8e29-c1681f03feb0", "1a9cbce7-0788-430e-b3e7-15bbbea2ac27") // <- пишем данные в буфер (блок с данными)
	err = tx.Commit() // <- отправляем на сервер
	if err != nil {
		log.Fatal(err)
	}
}
```
Не работает - пишет 
```
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][hello] -> Golang SQLDriver 1.1.54126
[clickhouse][hello] <- ClickHouse 1.1.54164 (Europe/Kiev)
[clickhouse]-> ping
[clickhouse]<- pong
[clickhouse][begin] tx=false, data=false
[clickhouse][prepare] INSERT INTO trackmanic2.events VALUES (?, ?)
[clickhouse][send query] INSERT INTO trackmanic2.events VALUES 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kshvakov/clickhouse.(*block).append(0xc4200d6000, 0xc42000c920, 0x2, 0x2, 0x64a3c8, 0x562d60)
        /home/dmitry/golang/src/github.com/kshvakov/clickhouse/block.go:203 +0x17c8
github.com/kshvakov/clickhouse.(*stmt).execContext(0xc420016b40, 0x633300, 0xc420010270, 0xc42000c920, 0x2, 0x2, 0x10000c420012c00, 0x10175ce911b, 0x2, 0x59422c)
        /home/dmitry/golang/src/github.com/kshvakov/clickhouse/stmt.go:31 +0x60
github.com/kshvakov/clickhouse.(*stmt).ExecContext(0xc420016b40, 0x633300, 0xc420010270, 0xc42001c460, 0x2, 0x2, 0xc400000008, 0xc42009e0c0, 0xc42004fc80, 0x4b9965)
        /home/dmitry/golang/src/github.com/kshvakov/clickhouse/clickhouse_go18.go:38 +0x1aa
database/sql.ctxDriverStmtExec(0x633300, 0xc420010270, 0x633400, 0xc420016b40, 0xc42001c460, 0x2, 0x2, 0x0, 0x0, 0x595ca8, ...)
        /usr/local/go/src/database/sql/ctxutil.go:66 +0x244
database/sql.resultFromStatement(0x633300, 0xc420010270, 0xc420018500, 0xc42004ff28, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1841 +0x193
database/sql.(*Stmt).ExecContext(0xc420020380, 0x633300, 0xc420010270, 0xc42004ff28, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1802 +0x252
database/sql.(*Stmt).Exec(0xc420020380, 0xc42004ff28, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42004ff08)
        /usr/local/go/src/database/sql/sql.go:1814 +0x65
main.main()
        /home/dmitry/golang/src/main/main.go:31 +0x48b
```
Получается эту ситуацию исправить, указав колонки для вставки
```
	stmt, err := tx.Prepare(`INSERT INTO trackmanic2.events (id,  origin_id) VALUES (?, ?)`)
	stmt.Exec("8cd3e02c-83b1-41f0-8e29-c1681f03feb0", "1a9cbce7-0788-430e-b3e7-15bbbea2ac27")
```
Есть ли возможность не указывать колонки?

**Comment by kshvakov** [comment]
Нет, если не указать, то КХ будет ожидать что они придут все и в том порядке в котором они созданы в таблице. Сделаю чтоб в данном случае возвращалась ошибка с описанием проблемы, а не паника

**Comment by dmitry-medvediev** [comment]
Да, это бы было хорошо. Спасибо большое.

**Comment by kshvakov** [comment]
done
