### ISSUE TITLE
Weird errors while selecting data

### ISSUE THREAD

**Issue by Civil** [kshvakov/clickhouse#23]
Table definition:
```SQL
CREATE TABLE IF NOT EXISTS flamegraph (
                        timestamp Int64,
                        graph_type String,
                        cluster String,
                        id UInt64,
                        name String,
                        total UInt64,
                        value UInt64,
                        children_ids Array(UInt64),
                        date Date
                ) engine=MergeTree(date, (timestamp, graph_type, cluster, value, date), 8192)
```

Then I fill it out with data (several million queries).

Then I'm trying to select data from it from a go program:
```Go
        rows, err := connect.Query("SELECT total FROM flamegraph WHERE timestamp=" + ts + " AND id = " + idQuery + " AND cluster='" + cluster + "'")
	total := uint64(0)
	for rows.Next() {
		err = rows.Scan(&total)
		if err != nil {
			log.Fatal(err)
		}
	}

	minValue := uint64(float64(total) * removeLowestPct)
	minValueQuery := strconv.FormatUint(minValue, 10)

	rows, err = connect.Query("SELECT timestamp, graph_type, cluster, id, name, total, value, children_ids FROM flamegraph WHERE timestamp=" + ts + " AND cluster='" + cluster + "' AND value > " + minValueQuery)
	if err != nil {
		log.Fatal(err)
	}
```

This results in the following queries:
```SQL
SELECT timestamp, graph_type, cluster, id, name, total, value, children_ids FROM flamegraph WHERE timestamp=1490791477 AND cluster='example' AND value > 4778
```

But each time I do that I got the following output:
```
[clickhouse][receive packet] <- data: columns=8, rows=0
[clickhouse][receive packet] err: unhandled type abnormal
[clickhouse][stmt] close
```

```
[clickhouse][receive packet] <- data: columns=8, rows=0
[clickhouse][receive packet] err: unhandled type all
[clickhouse][stmt] close
```

It seems that 'all', 'abnormal', etc is one of the names from the select.

At this moment I was unable to create a minimal test case for that.

**Comment by Civil** [comment]
Go: 1.8
Clickhouse: 1.1.54190

Bug goes away if I do:
```diff
--- a/block.go
+++ b/block.go
@@ -108,6 +108,7 @@ func (b *block) read(revision uint64, r io.Reader) error {
                        return err
                }
                // Coerce column type to Go type
+               fmt.Printf("%+v", b)
                columnInfo, err := toColumnType(columnType)
                if err != nil {
                        return err
```

**Comment by Civil** [comment]
In case I'll add a stacktrace to 'toColumnType' function it will print the following information:
```Go
goroutine 21 [running]:
runtime/debug.Stack(0xc42020a820, 0xc420194b60, 0xc4201dc0e0)
        /Users/vsmirnov/gentoo/usr/lib/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /Users/vsmirnov/gentoo/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/kshvakov/clickhouse.toColumnType(0xc4202664f0, 0x8, 0xc4202664f0, 0x8, 0x0, 0x0)
        /Users/vsmirnov/go/gopath_third_party/src/github.com/kshvakov/clickhouse/helpers.go:178 +0x3d4
github.com/kshvakov/clickhouse.(*block).read(0xc42020ac58, 0xd3ad, 0x8e7dc0, 0xc4200f3880, 0x0, 0x0)
        /Users/vsmirnov/go/gopath_third_party/src/github.com/kshvakov/clickhouse/block.go:111 +0x1ed
github.com/kshvakov/clickhouse.(*clickhouse).receiveData(0xc4201aa140, 0xc4200baf00, 0x9c, 0x0)
        /Users/vsmirnov/go/gopath_third_party/src/github.com/kshvakov/clickhouse/clickhouse_receive_data.go:28 +0x51d
github.com/kshvakov/clickhouse.(*stmt).queryContext(0xc4201b4990, 0x8ed000, 0xc42000e690, 0x935768, 0x0, 0x0, 0x30, 0x0, 0x0, 0x427c66)
        /Users/vsmirnov/go/gopath_third_party/src/github.com/kshvakov/clickhouse/stmt.go:81 +0x423
github.com/kshvakov/clickhouse.(*stmt).QueryContext(0xc4201b4990, 0x8ed000, 0xc42000e690, 0x935768, 0x0, 0x0, 0xc400000008, 0xc420014880, 0xc42020b1a8, 0x6af34a)
        /Users/vsmirnov/go/gopath_third_party/src/github.com/kshvakov/clickhouse/clickhouse_go18.go:30 +0x1ff
database/sql.ctxDriverStmtQuery(0x8ed000, 0xc42000e690, 0x8ed240, 0xc4201b4990, 0x935768, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/vsmirnov/gentoo/usr/lib/go/src/database/sql/ctxutil.go:83 +0x244
database/sql.rowsiFromStatement(0x8ed000, 0xc42000e690, 0xc420014d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/vsmirnov/gentoo/usr/lib/go/src/database/sql/sql.go:2002 +0x1eb
database/sql.(*DB).queryConn(0xc4201e6140, 0x8ed000, 0xc42000e690, 0xc420071110, 0xc4201c6930, 0xc4200bad20, 0x9c, 0x0, 0x0, 0x0, ...)
        /Users/vsmirnov/gentoo/usr/lib/go/src/database/sql/sql.go:1294 +0x259
database/sql.(*DB).query(0xc4201e6140, 0x8ed000, 0xc42000e690, 0xc4200bad20, 0x9c, 0x0, 0x0, 0x0, 0x1, 0x9c, ...)
        /Users/vsmirnov/gentoo/usr/lib/go/src/database/sql/sql.go:1250 +0x12f
database/sql.(*DB).QueryContext(0xc4201e6140, 0x8ed000, 0xc42000e690, 0xc4200bad20, 0x9c, 0x0, 0x0, 0x0, 0xc42020d748, 0x0, ...)
        /Users/vsmirnov/gentoo/usr/lib/go/src/database/sql/sql.go:1227 +0xb8
database/sql.(*DB).Query(0xc4201e6140, 0xc4200bad20, 0x9c, 0x0, 0x0, 0x0, 0xc4200a6800, 0x0, 0x0)
        /Users/vsmirnov/gentoo/usr/lib/go/src/database/sql/sql.go:1241 +0x82
main.getHandler(0x8ecac0, 0xc4201f8000, 0xc4201f2000)
        /Users/vsmirnov/go/gopath_third_party/src/github.com/Civil/carbonserver-flamegraphs/main.go:521 +0x1de2
net/http.HandlerFunc.ServeHTTP(0x7975d0, 0x8ecac0, 0xc4201f8000, 0xc4201f2000)
        /Users/vsmirnov/gentoo/usr/lib/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420013860, 0x8ecac0, 0xc4201f8000, 0xc4201f2000)
        /Users/vsmirnov/gentoo/usr/lib/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200cc420, 0x8ecac0, 0xc4201f8000, 0xc4201f2000)
        /Users/vsmirnov/gentoo/usr/lib/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201e60a0, 0x8ecfc0, 0xc4201be300)
        /Users/vsmirnov/gentoo/usr/lib/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /Users/vsmirnov/gentoo/usr/lib/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by Civil** [comment]
I've built the sources with '-race' flag, but it seems that everything is in order (no races reported).

**Comment by kshvakov** [comment]
At this moment I was not able to reproduce the problem. I will try to investigate the problem 

```
:) select version();

SELECT version()

┌─version()─┐
│ 1.1.54187 │
└───────────┘
```
```
go version go1.8 linux/amd64
```

output 

```
[clickhouse][prepare] SELECT timestamp, graph_type, cluster, id, name, total, value, children_ids FROM flamegraph WHERE timestamp>25 AND cluster='cluster' AND value > 4778
[clickhouse][send query] SELECT timestamp, graph_type, cluster, id, name, total, value, children_ids FROM flamegraph WHERE timestamp>25 AND cluster='cluster' AND value > 4778
[clickhouse][receive packet] <- data: columns=8, rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- progress: rows=72482816, bytes=647168, total rows=1007616
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- progress: rows=7340032, bytes=65536, total rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65436
[clickhouse][receive packet] <- progress: rows=7340032, bytes=65536, total rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- progress: rows=7340032, bytes=65536, total rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- progress: rows=6422528, bytes=57344, total rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- progress: rows=6422528, bytes=57344, total rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- progress: rows=4696832, bytes=41936, total rows=0
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- data: columns=8, rows=57344
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- data: columns=8, rows=65536
[clickhouse][receive packet] <- data: columns=8, rows=57344
[clickhouse][receive packet] <- data: columns=8, rows=57344
[clickhouse][receive packet] <- data: columns=8, rows=41936
[clickhouse][receive packet] <- profiling: rows=1000300, bytes=16, blocks=112033600
[clickhouse][receive packet] <- progress: rows=0, bytes=0, total rows=0
[clickhouse][receive packet] <- data: columns=0, rows=0
[clickhouse][receive packet] <- end of stream

```

**Comment by Civil** [comment]
It have something to do with the dataset, but I unfortunately can't dump the table. It only happens for one of the clusters (for any timestamps, but bug goes away if I add anything that can slow down the execution), but not for the other.

**Comment by kshvakov** [comment]
Hmm, that's weird. Does the clickhouse-client perform such requests correctly?

**Comment by Civil** [comment]
Yes, it does.

**Comment by kshvakov** [comment]
I managed to reproduce this bug

**Comment by kshvakov** [comment]
Done, please check

**Comment by Civil** [comment]
Seems to be working now! Thanks!

**Comment by kenota** [comment]
Hi, it seems that I am having very similar experience but with multiple go-routines doing inserts into 3 different tables using 3 clickhouse server connections. 

It usually runs fine for some time, but then it always fails on Prepare() call with the same error message specifying parts of the fields from INSERT query, for example:

func toColumnType: unhandled type tring(36)

Where in requests there is a FixedString(36) type field. Looking at the code it is like something is affecting packts read from the server on Prepare?  

Also is it safe to use multiple instances of clickhouse client received from .Open()?

**Comment by kshvakov** [comment]
Multiple instances should be safe. Please, give an example of the code to reproduce the error

**Comment by kenota** [comment]
I've been trying to write simple code to reproduce the problem -- 3 go routines writing random data to the 3 tables with same structure with no luck so far. Which potentially indicates that may be there is bug in my code. I will keep this thread updated.

Thanks for quick reply.

**Comment by kenota** [comment]
I was able to reproduce the problem, since it is not select, I have created new issue #34
