### ISSUE TITLE
Panic when calling rs.ColumnTypes()

### ISSUE THREAD

**Issue by joanbalaguero** [kshvakov/clickhouse#81]
Hi,

A call to ColumnTypes() in a *sql.Rows returns this:

2017/12/27 23:01:15 http: panic serving 172.17.0.1:36840: runtime error: index out of range
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc42016e000)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x702340, 0x919830)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/kshvakov/clickhouse.(*rows).ColumnTypeScanType(0xc420178120, 0x0, 0xc420178120, 0x7f5e7c337398)
        /go/src/github.com/kshvakov/clickhouse/rows.go:35 +0x71
database/sql.rowsColumnInfoSetup(0x8ee5e0, 0xc420178120, 0xc42016a130, 0x3, 0x3)
        /usr/local/go/src/database/sql/sql.go:2635 +0x17b
database/sql.(*Rows).ColumnTypes(0xc42016a100, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:2563 +0x14f
query-service/utils.GetResultAsMap(0xc42016a100, 0x77b8b0, 0xc42016a100, 0x5, 0xc42016a100)
        /go/src/query-service/utils/queries.go:187 +0x6e
query-service/utils.ExecuteQueryAndGetResultAsMap(0xc42016e3c0, 0xc420186000, 0x7664f9, 0x5, 0x0, 0x0, 0x0, 0x0)
        /go/src/query-service/utils/queries.go:177 +0xc3

Joan.

**Comment by kshvakov** [comment]
Hi, checkout master and check it, please
