### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gekpp** [kshvakov/clickhouse#90]
Hi. I've got such an error while saving data to clickhouse to Buffer table. (sorry for long lines). 
I'm writing batch of 10K entries to the buffer. I guess that the size could be a cause of the problem but i'm not sure.
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x458667]

goroutine 51 [running]:
landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/writebuffer.(*WriteBuffer).Write(0xc4a3a5a8e0, 0x0, 0x15, 0x15, 0x0, 0x0, 0x118b)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/writebuffer/buffer.go:31 +0x2f0
landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Encoder).String(0xc4a3a5a940, 0x0, 0x15, 0x1, 0x1)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/binary/encoder.go:109 +0xa9
landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/column.(*String).Write(0xc4b5b0f900, 0xc4a3a5a940, 0x767500, 0xc4aef0df90, 0x1, 0x0)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/column/string.go:20 +0x147
landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/column.(*Nullable).WriteNull(0xc48c61b540, 0xc4a3a5a920, 0xc4a3a5a940, 0x767500, 0xc4aef0df90, 0x0, 0x782980)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/column/nullable.go:63 +0xcc
landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/data.(*Block).AppendRow(0xc4a1254960, 0xc4a32ac780, 0xc, 0xc, 0x1, 0xc4a32ac780)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/lib/data/block.go:115 +0x290
landings-crawler/vendor/github.com/kshvakov/clickhouse.(*stmt).execContext(0xc490e646f0, 0xa40640, 0xc420016028, 0xc4a32ac780, 0xc, 0xc, 0x1016621b840, 0x0, 0xc4b68e5f60, 0x41143d)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/stmt.go:46 +0x6b
landings-crawler/vendor/github.com/kshvakov/clickhouse.(*stmt).ExecContext(0xc490e646f0, 0xa40640, 0xc420016028, 0xc4a32ae000, 0xc, 0xc, 0xc46621b858, 0xa3e4a8, 0x0, 0x65a0d6)
        /landings-crawler/vendor/github.com/kshvakov/clickhouse/stmt.go:40 +0x1ac
database/sql.ctxDriverStmtExec(0xa40640, 0xc420016028, 0xa40880, 0xc490e646f0, 0xc4a32ae000, 0xc, 0xc, 0xc, 0xc, 0x0, ...)
        /usr/local/go/src/database/sql/ctxutil.go:66 +0x22e
database/sql.resultFromStatement(0xa40640, 0xc420016028, 0xa3fec0, 0xc420434750, 0xc4b5b0fac0, 0xc4b68e63a0, 0xc, 0xc, 0x0, 0x0, ...)
        /usr/local/go/src/database/sql/sql.go:2109 +0x184
database/sql.(*Stmt).ExecContext(0xc454bf4480, 0xa40640, 0xc420016028, 0xc4b68e63a0, 0xc, 0xc, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:2085 +0x223
database/sql.(*Stmt).Exec(0xc454bf4480, 0xc4b68e63a0, 0xc, 0xc, 0xa3f2c0, 0xc4a6b85920, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:2097 +0x65
landings-crawler/internal/savers.(*BundleSaver).saveAdverts(0xc4204e0180, 0xc4b2ff6000, 0x2710, 0x2710, 0x0, 0x0)
        /landings-crawler/internal/savers/bundle_saver.go:308 +0x57b

**Comment by kshvakov** [comment]
Can you make a small example code to reproduce this bug?

**Comment by gekpp** [comment]
Table schema is:
```
CREATE TABLE v2_dicts_shard.advert
(
	id UInt64,
	type UInt8,
	width Int16,
	height Int16,
	title Nullable(String),
	text Nullable(String),
	media_url Nullable(String),
	visible_url Nullable(String),
	landing_url String,
	content_check_sum String,
	day Date,
        sign Int8
)
ENGINE = CollapsingMergeTree (
  day,
  id,
  8192,
  sign
);

CREATE TABLE v2_dicts_shard.advert_buffer
AS v2_dicts_shard.advert
ENGINE = Buffer('v2_dicts_shard', 'advert', 16, 10, 100, 10000, 1000000, 10000000, 100000000);
```

The writer code is:
```
import	"github.com/pkg/errors"

type Advert struct {
	Id              uint64    `db:"id",validate:"required"`
	Type            uint8     `db:"type",validate:"gte=0"`
	Width           int16     `db:"width"`
	Height          int16     `db:"height"`
	Title           string    `db:"title"`
	Text            string    `db:"text"`
	MediaUrl        string    `db:"media_url"`
	VisibleUrl      string    `db:"visible_url"`
	LandingUrl      string    `db:"landing_url",validate:"required"`
	ContentCheckSum string    `db:"content_check_sum",validate:"required"`
	Day             time.Time `db:"day"`
	Sign            int8      `db:"sign"`
}

type BundleSaver struct {
	db             *sqlx.DB
	dictsDbName    string
}

func (s *BundleSaver) saveAdverts(ads []Advert) (resErr error) {
	log.Printf("Saving %d adverts", len(ads))
	defer log.Println("Saving adverts DONE")

	query := fmt.Sprintf(`INSERT INTO %s.advert_buffer
(id, type, width, height, title, text, media_url, visible_url, landing_url, content_check_sum, day, sign)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, s.dictsDbName)
	tx, stmt, err := prepare(s.db, query)
	if err != nil {
		return errors.Wrap(err, "Prepare save adverts")
	}
	defer func() {
		if resErr != nil {
			tx.Rollback()
		}
	}()

	params := make([] interface{}, 12)
	for _, a := range ads {
		params[0] = a.Id
		params[1] = a.Type
		params[2] = a.Width
		params[3] = a.Height
		params[4] = a.Title
		params[5] = a.Text
		params[6] = a.MediaUrl
		params[7] = a.VisibleUrl
		params[8] = a.LandingUrl
		params[9] = a.ContentCheckSum
		params[10] = "2017-01-01"
		params[11] = 1
		if _, err := stmt.Exec(params...); err != nil {
			return errors.Wrap(err, "Save adverts")
		}
	}

	if err := tx.Commit(); err != nil {
		return errors.Wrap(err, "Commit adverts")
	}

	return nil
}

func prepare(db *sqlx.DB, query string) (*sqlx.Tx, *sqlx.Stmt, error) {
	tx, err := db.Beginx()
	if err != nil {
		return nil, nil, err
	}

	stmt, err := tx.Preparex(query)
	if err != nil {
		tx.Rollback()
		return tx, nil, err
	}
	return tx, stmt, err
}
```

Advert.MediaUrl can be long string - up to several KB
Hope this will help.

**Comment by gekpp** [comment]
I finally found bug in my program. The cause was a race condition. In some cases I call saveAdverts func with nil slice.
Please close the issue
